bug:
  - head-branch:
      - "^fix"

CI:
  - changed-files:
      - any-glob-to-any-file:
          - .github/**
          - .pre-commit-config.yaml
  - head-branch:
      - "^ci"
      - "^pre-commit-ci"

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - uv.lock
  - head-branch:
      - "^build(deps)"

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - docs/**
          - mkdocs.yml
          - readme.md
  - head-branch:
      - "^docs"

enhancement:
  - head-branch:
      - "^feat"

tests:
  - changed-files:
      - any-glob-to-any-file:
          - tests/**
  - head-branch:
      - "^test"

BREAKING CHANGE:
  - head-branch:
      - "^(?:fix|feat|refactor)!"

"component: base":
  - changed-files:
      - any-glob-to-any-file:
          - src/polyany/base.py

"component: polynomial":
  - changed-files:
      - any-glob-to-any-file:
          - src/polyany/polynomial.py

"component: matrix":
  - changed-files:
      - any-glob-to-any-file:
          - src/polyany/matrix.py

"component: functions":
  - changed-files:
      - any-glob-to-any-file:
          - src/polyany/functions.py
