site_name: PolyAny
site_url: https://rolmip.github.io/polyany
site_author: Cristiano Agulhari, Esdras Battosti
site_description: A Python package for algebraic manipulation of multivariate polynomials
repo_url: https://github.com/rolmip/polyany
repo_name: rolmip/polyany
edit_uri: edit/main/docs/
theme:
  language: en
  name: material
  custom_dir: docs/overrides
  palette:
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/white-balance-sunny
        name: Switch to light mode
      primary: custom
      accent: custom

    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
      primary: custom
      accent: custom
  font:
    text: Inter
    code: JetBrains Mono
  logo: assets/logo_white.svg
  favicon: assets/logo_purple.svg
  features:
    - navigation.tracking
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.share
    - search.highlight
    - content.code.copy
    - content.code.annotate
    - content.action.view
    - content.action.edit
    - content.tooltips

plugins:
  - search
  - macros
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          inventories:
            - https://docs.python.org/3/objects.inv
            - https://numpy.org/doc/stable/objects.inv
          paths: [src]
          options:
            show_source: false
            docstring_style: numpy
            show_root_heading: true
            show_root_full_path: false
            merge_init_into_class: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
            docstring_section_style: spacy

nav:
  - PolyAny: index.md
  - Installation: installation.md
  - Getting Started: "getting_started.md"
  - API reference: "api.md"

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_css:
  - css/extra.css

extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

extra:
  polyany: <span class="polyany">PolyAny</span>

copyright:
  Copyright &copy; 2025 Cristiano Agulhari and Esdras Battosti
