name: Bump and Release

on:
  push:
    branches: [main]

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: "Bump version and create changelog with commitizen"
    steps:
      - name: Check out
        uses: actions/checkout@v5
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: body.md
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Build
        run: uv build
      - name: Release
        uses: softprops/action-gh-release@fbadcc90e88ecface60a0a0d123795b784ceb239
        with:
          body_path: "body.md"
          tag_name: ${{ env.REVISION }}
          files: |
            dist/*.tar.gz
            dist/*.whl
          overwrite_files: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
