name: Upload Python Package

on:
  push:
    tags:
      - "*"

jobs:
  pypi:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi_release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@e8d4307400f9427dba7cb98e488d6ab85f1cec5f
      - uses: astral-sh/setup-uv@6a191366842ac1502ba6c07e9b5acd5c2d9d8db3
      - run: uv build
      - name: Smoke test (wheel)
        run: uv run --isolated --no-project --with dist/*.whl tests/smoke_test.py
      - name: Smoke test (source distribution)
        run: uv run --isolated --no-project --with dist/*.tar.gz tests/smoke_test.py
      - name: Publish
        run: uv publish --trusted-publishing always
